### ISSUE TITLE
Error in tempdir(check = TRUE) : unused argument (check = TRUE)

### ISSUE THREAD

**Issue by kkougiou** [mkearney/pkgverse#3]
This error keeps popping up, even when running the example provided in the README file

**Comment by aimeegott** [comment]
I had the same issue, seems there has been a change to the function at R 3.5.0 and there is now a check argument that wasn't there before

**Comment by mkearney** [comment]
thanks, @aimeegott, I was actually rather clueless on this!

**Comment by mkearney** [comment]
`check = TRUE` is now conditional on having at least R version `3.5.0`: https://github.com/mkearney/pkgverse/blob/d0472b4b6c123af19576912cdbc01deeb8a3f766/R/pkgverse.R#L96
