### ISSUE TITLE
Error in refuse_package(package, verboten = "tidyverse")

### ISSUE THREAD

**Issue by IndrajeetPatil** [mkearney/pkgverse#8]
If I have already created a package project in RStudio (https://github.com/IndrajeetPatil/ggverse) and I am inside the root directory for the package, how can I then create a `verse`-package? That is, it will replace the existing `DESCRIPTION` file and also add the needed `.R` files.
Should I set `keep = FALSE`?

Because if I do so, I get the following error-
```r
pkgverse::pkgverse(
  pkg = "ggverse",       # RStudio project name for the package
  pkgs = ggverse::ggpackages_cran$Package, # vector of packages
  use = "package",       # add used packages using `usethis::use_package()`
  keep = FALSE,
  install_if = TRUE
)

Error in refuse_package(package, verboten = "tidyverse") : 
  argument "package" is missing, with no default
```

**Comment by jgcolman** [comment]
I can't answer your specific question, but when I just got the mysterious verboten error it had been caused by my failing to enclose a package name in "".
